---
language: node_js
node_js:
  - '10'
  - node

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: lint
      script:
        - npm install
        - npm install eslint -g
        - npm run lint
    - stage: test
      script:
        - npm run test
        